### ISSUE TITLE
Update translations for 0.4.0

### ISSUE THREAD

**Issue by rafaelmardojai** [rafaelmardojai/blanket#97]
I'm going to release 0.4.0 soon, if you have time to update the translations would be very awesome.

Thanks in advance!

- [x] Catalan @fitojb
- [x] German @eladyn
- [x] Esperanto @Porrumentzio
- [x] Spanish @rafaelmardojai 
- [x] Basque @Porrumentzio
- [x] French @maoschanz @julroy67
- [x] Croatian @milotype
- [x] Italian @albanobattistella
- [x] Nepali @IBA4
- [x] Dutch @Vistaus
- [x] Brazilian Portuguese @pedrofleck
- [x] Slovak @MartinIIOT
- [x] Ukrainian @IhorHordiichuk

**Comment by Porrumentzio** [comment]
Wow, this has grown a lot! Basque and Esperanto done!

**Comment by Vistaus** [comment]
Done! 🙂 #101

**Comment by pedrofleck** [comment]
Hey, @rafaelmardojai, just letting you know that I'm still on board! First thing I'll be doing tomorrow.

**Comment by rafaelmardojai** [comment]
@maoschanz @julroy67 @milotype Hey guys I'm ping you in case you missed it. In case you don't have time just let me know.
